FROM node:18-buster-slim

WORKDIR /app

RUN npm install -g dynamodb-admin

EXPOSE 8001

CMD ["sh", "-c", "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_REGION=$AWS_REGION DYNAMODB_ENDPOINT=$DYNAMODB_ENDPOINT dynamodb-admin"]
