#!/bin/sh

export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
export AWS_REGION=$AWS_REGION
export DYNAMO_ENDPOINT=$DYNAMO_ENDPOINT

echo "Using endpoint: $DYNAMO_ENDPOINT"

dynamodb-admin
